spring:
  datasource:
    url: jdbc:postgresql://localhost:6543/phat_store
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

server:
  port: 9000

debug: true